# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_module/protos/led.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brpc_module/protos/led.proto\x12\rEdgePiRPC_LED\"E\n\x07LEDName\x12-\n\x08led_name\x18\x01 \x01(\x0e\x32\x16.EdgePiRPC_LED.LEDPinsH\x00\x88\x01\x01\x42\x0b\n\t_led_name\".\n\nSuccessMsg\x12\x14\n\x07\x63ontent\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_content*Y\n\x07LEDPins\x12\x08\n\x04LED1\x10\x00\x12\x08\n\x04LED2\x10\x01\x12\x08\n\x04LED3\x10\x02\x12\x08\n\x04LED4\x10\x03\x12\x08\n\x04LED5\x10\x04\x12\x08\n\x04LED6\x10\x05\x12\x08\n\x04LED7\x10\x06\x12\x08\n\x04LED8\x10\x07\x32\xd2\x01\n\nLEDService\x12@\n\x0bturn_led_on\x12\x16.EdgePiRPC_LED.LEDName\x1a\x19.EdgePiRPC_LED.SuccessMsg\x12\x41\n\x0cturn_led_off\x12\x16.EdgePiRPC_LED.LEDName\x1a\x19.EdgePiRPC_LED.SuccessMsg\x12?\n\ntoggle_led\x12\x16.EdgePiRPC_LED.LEDName\x1a\x19.EdgePiRPC_LED.SuccessMsgB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_module.protos.led_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\001\001'
  _globals['_LEDPINS']._serialized_start=165
  _globals['_LEDPINS']._serialized_end=254
  _globals['_LEDNAME']._serialized_start=46
  _globals['_LEDNAME']._serialized_end=115
  _globals['_SUCCESSMSG']._serialized_start=117
  _globals['_SUCCESSMSG']._serialized_end=163
  _globals['_LEDSERVICE']._serialized_start=257
  _globals['_LEDSERVICE']._serialized_end=467
_builder.BuildServices(DESCRIPTOR, 'rpc_module.protos.led_pb2', _globals)
# @@protoc_insertion_point(module_scope)
