# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: led.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='led.proto',
  package='EdgePiRPC_LED',
  syntax='proto3',
  serialized_options=b'\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tled.proto\x12\rEdgePiRPC_LED\"B\n\x06LEDPin\x12,\n\x07led_pin\x18\x01 \x01(\x0e\x32\x16.EdgePiRPC_LED.LEDPinsH\x00\x88\x01\x01\x42\n\n\x08_led_pin\".\n\nSuccessMsg\x12\x14\n\x07\x63ontent\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_content*Y\n\x07LEDPins\x12\x08\n\x04LED1\x10\x00\x12\x08\n\x04LED2\x10\x01\x12\x08\n\x04LED3\x10\x02\x12\x08\n\x04LED4\x10\x03\x12\x08\n\x04LED5\x10\x04\x12\x08\n\x04LED6\x10\x05\x12\x08\n\x04LED7\x10\x06\x12\x08\n\x04LED8\x10\x07\x32\xcf\x01\n\nLEDService\x12?\n\x0bturn_led_on\x12\x15.EdgePiRPC_LED.LEDPin\x1a\x19.EdgePiRPC_LED.SuccessMsg\x12@\n\x0cturn_led_off\x12\x15.EdgePiRPC_LED.LEDPin\x1a\x19.EdgePiRPC_LED.SuccessMsg\x12>\n\ntoggle_led\x12\x15.EdgePiRPC_LED.LEDPin\x1a\x19.EdgePiRPC_LED.SuccessMsgB\x03\x90\x01\x01\x62\x06proto3'
)

_LEDPINS = _descriptor.EnumDescriptor(
  name='LEDPins',
  full_name='EdgePiRPC_LED.LEDPins',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LED1', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED2', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED3', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED4', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED5', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED6', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED7', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LED8', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=144,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_LEDPINS)

LEDPins = enum_type_wrapper.EnumTypeWrapper(_LEDPINS)
LED1 = 0
LED2 = 1
LED3 = 2
LED4 = 3
LED5 = 4
LED6 = 5
LED7 = 6
LED8 = 7



_LEDPIN = _descriptor.Descriptor(
  name='LEDPin',
  full_name='EdgePiRPC_LED.LEDPin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='led_pin', full_name='EdgePiRPC_LED.LEDPin.led_pin', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_led_pin', full_name='EdgePiRPC_LED.LEDPin._led_pin',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=28,
  serialized_end=94,
)


_SUCCESSMSG = _descriptor.Descriptor(
  name='SuccessMsg',
  full_name='EdgePiRPC_LED.SuccessMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='EdgePiRPC_LED.SuccessMsg.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_content', full_name='EdgePiRPC_LED.SuccessMsg._content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=96,
  serialized_end=142,
)

_LEDPIN.fields_by_name['led_pin'].enum_type = _LEDPINS
_LEDPIN.oneofs_by_name['_led_pin'].fields.append(
  _LEDPIN.fields_by_name['led_pin'])
_LEDPIN.fields_by_name['led_pin'].containing_oneof = _LEDPIN.oneofs_by_name['_led_pin']
_SUCCESSMSG.oneofs_by_name['_content'].fields.append(
  _SUCCESSMSG.fields_by_name['content'])
_SUCCESSMSG.fields_by_name['content'].containing_oneof = _SUCCESSMSG.oneofs_by_name['_content']
DESCRIPTOR.message_types_by_name['LEDPin'] = _LEDPIN
DESCRIPTOR.message_types_by_name['SuccessMsg'] = _SUCCESSMSG
DESCRIPTOR.enum_types_by_name['LEDPins'] = _LEDPINS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LEDPin = _reflection.GeneratedProtocolMessageType('LEDPin', (_message.Message,), {
  'DESCRIPTOR' : _LEDPIN,
  '__module__' : 'led_pb2'
  # @@protoc_insertion_point(class_scope:EdgePiRPC_LED.LEDPin)
  })
_sym_db.RegisterMessage(LEDPin)

SuccessMsg = _reflection.GeneratedProtocolMessageType('SuccessMsg', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSMSG,
  '__module__' : 'led_pb2'
  # @@protoc_insertion_point(class_scope:EdgePiRPC_LED.SuccessMsg)
  })
_sym_db.RegisterMessage(SuccessMsg)


DESCRIPTOR._options = None

_LEDSERVICE = _descriptor.ServiceDescriptor(
  name='LEDService',
  full_name='EdgePiRPC_LED.LEDService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=443,
  methods=[
  _descriptor.MethodDescriptor(
    name='turn_led_on',
    full_name='EdgePiRPC_LED.LEDService.turn_led_on',
    index=0,
    containing_service=None,
    input_type=_LEDPIN,
    output_type=_SUCCESSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='turn_led_off',
    full_name='EdgePiRPC_LED.LEDService.turn_led_off',
    index=1,
    containing_service=None,
    input_type=_LEDPIN,
    output_type=_SUCCESSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='toggle_led',
    full_name='EdgePiRPC_LED.LEDService.toggle_led',
    index=2,
    containing_service=None,
    input_type=_LEDPIN,
    output_type=_SUCCESSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEDSERVICE)

DESCRIPTOR.services_by_name['LEDService'] = _LEDSERVICE

LEDService = service_reflection.GeneratedServiceType('LEDService', (_service.Service,), dict(
  DESCRIPTOR = _LEDSERVICE,
  __module__ = 'led_pb2'
  ))

LEDService_Stub = service_reflection.GeneratedServiceStubType('LEDService_Stub', (LEDService,), dict(
  DESCRIPTOR = _LEDSERVICE,
  __module__ = 'led_pb2'
  ))


# @@protoc_insertion_point(module_scope)
