# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relay.proto',
  package='EdgePiRPC_Relay',
  syntax='proto3',
  serialized_options=b'\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0brelay.proto\x12\x0f\x45\x64gePiRPC_Relay\"\n\n\x08\x45mptyMsg\".\n\nSuccessMsg\x12\x14\n\x07\x63ontent\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_content\"/\n\x05State\x12\x17\n\nstate_bool\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\r\n\x0b_state_bool2\xe1\x01\n\x0cRelayService\x12\x44\n\nopen_relay\x12\x19.EdgePiRPC_Relay.EmptyMsg\x1a\x1b.EdgePiRPC_Relay.SuccessMsg\x12\x45\n\x0b\x63lose_relay\x12\x19.EdgePiRPC_Relay.EmptyMsg\x1a\x1b.EdgePiRPC_Relay.SuccessMsg\x12\x44\n\x0fget_state_relay\x12\x19.EdgePiRPC_Relay.EmptyMsg\x1a\x16.EdgePiRPC_Relay.StateB\x03\x90\x01\x01\x62\x06proto3'
)




_EMPTYMSG = _descriptor.Descriptor(
  name='EmptyMsg',
  full_name='EdgePiRPC_Relay.EmptyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=42,
)


_SUCCESSMSG = _descriptor.Descriptor(
  name='SuccessMsg',
  full_name='EdgePiRPC_Relay.SuccessMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='EdgePiRPC_Relay.SuccessMsg.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_content', full_name='EdgePiRPC_Relay.SuccessMsg._content',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=44,
  serialized_end=90,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='EdgePiRPC_Relay.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_bool', full_name='EdgePiRPC_Relay.State.state_bool', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_state_bool', full_name='EdgePiRPC_Relay.State._state_bool',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=92,
  serialized_end=139,
)

_SUCCESSMSG.oneofs_by_name['_content'].fields.append(
  _SUCCESSMSG.fields_by_name['content'])
_SUCCESSMSG.fields_by_name['content'].containing_oneof = _SUCCESSMSG.oneofs_by_name['_content']
_STATE.oneofs_by_name['_state_bool'].fields.append(
  _STATE.fields_by_name['state_bool'])
_STATE.fields_by_name['state_bool'].containing_oneof = _STATE.oneofs_by_name['_state_bool']
DESCRIPTOR.message_types_by_name['EmptyMsg'] = _EMPTYMSG
DESCRIPTOR.message_types_by_name['SuccessMsg'] = _SUCCESSMSG
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMsg = _reflection.GeneratedProtocolMessageType('EmptyMsg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMSG,
  '__module__' : 'relay_pb2'
  # @@protoc_insertion_point(class_scope:EdgePiRPC_Relay.EmptyMsg)
  })
_sym_db.RegisterMessage(EmptyMsg)

SuccessMsg = _reflection.GeneratedProtocolMessageType('SuccessMsg', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSMSG,
  '__module__' : 'relay_pb2'
  # @@protoc_insertion_point(class_scope:EdgePiRPC_Relay.SuccessMsg)
  })
_sym_db.RegisterMessage(SuccessMsg)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'relay_pb2'
  # @@protoc_insertion_point(class_scope:EdgePiRPC_Relay.State)
  })
_sym_db.RegisterMessage(State)


DESCRIPTOR._options = None

_RELAYSERVICE = _descriptor.ServiceDescriptor(
  name='RelayService',
  full_name='EdgePiRPC_Relay.RelayService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=142,
  serialized_end=367,
  methods=[
  _descriptor.MethodDescriptor(
    name='open_relay',
    full_name='EdgePiRPC_Relay.RelayService.open_relay',
    index=0,
    containing_service=None,
    input_type=_EMPTYMSG,
    output_type=_SUCCESSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='close_relay',
    full_name='EdgePiRPC_Relay.RelayService.close_relay',
    index=1,
    containing_service=None,
    input_type=_EMPTYMSG,
    output_type=_SUCCESSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_state_relay',
    full_name='EdgePiRPC_Relay.RelayService.get_state_relay',
    index=2,
    containing_service=None,
    input_type=_EMPTYMSG,
    output_type=_STATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RELAYSERVICE)

DESCRIPTOR.services_by_name['RelayService'] = _RELAYSERVICE

RelayService = service_reflection.GeneratedServiceType('RelayService', (_service.Service,), dict(
  DESCRIPTOR = _RELAYSERVICE,
  __module__ = 'relay_pb2'
  ))

RelayService_Stub = service_reflection.GeneratedServiceStubType('RelayService_Stub', (RelayService,), dict(
  DESCRIPTOR = _RELAYSERVICE,
  __module__ = 'relay_pb2'
  ))


# @@protoc_insertion_point(module_scope)
