# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: din.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='din.proto',
  package='EdgePiRPC_DIN',
  syntax='proto3',
  serialized_options=b'\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tdin.proto\x12\rEdgePiRPC_DIN\"B\n\x06\x44inPin\x12,\n\x07\x64in_pin\x18\x01 \x01(\x0e\x32\x16.EdgePiRPC_DIN.DinPinsH\x00\x88\x01\x01\x42\n\n\x08_din_pin\"/\n\x05State\x12\x17\n\nstate_bool\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\r\n\x0b_state_bool*Y\n\x07\x44inPins\x12\x08\n\x04\x44IN1\x10\x00\x12\x08\n\x04\x44IN2\x10\x01\x12\x08\n\x04\x44IN3\x10\x02\x12\x08\n\x04\x44IN4\x10\x03\x12\x08\n\x04\x44IN5\x10\x04\x12\x08\n\x04\x44IN6\x10\x05\x12\x08\n\x04\x44IN7\x10\x06\x12\x08\n\x04\x44IN8\x10\x07\x32P\n\nDinService\x12\x42\n\x13\x64igital_input_state\x12\x15.EdgePiRPC_DIN.DinPin\x1a\x14.EdgePiRPC_DIN.StateB\x03\x90\x01\x01\x62\x06proto3'
)

_DINPINS = _descriptor.EnumDescriptor(
  name='DinPins',
  full_name='EdgePiRPC_DIN.DinPins',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIN1', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIN2', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIN3', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIN4', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIN5', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIN6', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIN7', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIN8', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=145,
  serialized_end=234,
)
_sym_db.RegisterEnumDescriptor(_DINPINS)

DinPins = enum_type_wrapper.EnumTypeWrapper(_DINPINS)
DIN1 = 0
DIN2 = 1
DIN3 = 2
DIN4 = 3
DIN5 = 4
DIN6 = 5
DIN7 = 6
DIN8 = 7



_DINPIN = _descriptor.Descriptor(
  name='DinPin',
  full_name='EdgePiRPC_DIN.DinPin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='din_pin', full_name='EdgePiRPC_DIN.DinPin.din_pin', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_din_pin', full_name='EdgePiRPC_DIN.DinPin._din_pin',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=28,
  serialized_end=94,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='EdgePiRPC_DIN.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_bool', full_name='EdgePiRPC_DIN.State.state_bool', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_state_bool', full_name='EdgePiRPC_DIN.State._state_bool',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=96,
  serialized_end=143,
)

_DINPIN.fields_by_name['din_pin'].enum_type = _DINPINS
_DINPIN.oneofs_by_name['_din_pin'].fields.append(
  _DINPIN.fields_by_name['din_pin'])
_DINPIN.fields_by_name['din_pin'].containing_oneof = _DINPIN.oneofs_by_name['_din_pin']
_STATE.oneofs_by_name['_state_bool'].fields.append(
  _STATE.fields_by_name['state_bool'])
_STATE.fields_by_name['state_bool'].containing_oneof = _STATE.oneofs_by_name['_state_bool']
DESCRIPTOR.message_types_by_name['DinPin'] = _DINPIN
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.enum_types_by_name['DinPins'] = _DINPINS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DinPin = _reflection.GeneratedProtocolMessageType('DinPin', (_message.Message,), {
  'DESCRIPTOR' : _DINPIN,
  '__module__' : 'din_pb2'
  # @@protoc_insertion_point(class_scope:EdgePiRPC_DIN.DinPin)
  })
_sym_db.RegisterMessage(DinPin)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'din_pb2'
  # @@protoc_insertion_point(class_scope:EdgePiRPC_DIN.State)
  })
_sym_db.RegisterMessage(State)


DESCRIPTOR._options = None

_DINSERVICE = _descriptor.ServiceDescriptor(
  name='DinService',
  full_name='EdgePiRPC_DIN.DinService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=316,
  methods=[
  _descriptor.MethodDescriptor(
    name='digital_input_state',
    full_name='EdgePiRPC_DIN.DinService.digital_input_state',
    index=0,
    containing_service=None,
    input_type=_DINPIN,
    output_type=_STATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DINSERVICE)

DESCRIPTOR.services_by_name['DinService'] = _DINSERVICE

DinService = service_reflection.GeneratedServiceType('DinService', (_service.Service,), dict(
  DESCRIPTOR = _DINSERVICE,
  __module__ = 'din_pb2'
  ))

DinService_Stub = service_reflection.GeneratedServiceStubType('DinService_Stub', (DinService,), dict(
  DESCRIPTOR = _DINSERVICE,
  __module__ = 'din_pb2'
  ))


# @@protoc_insertion_point(module_scope)
