# This workflow will create a new tag based on latest commit to main branch
# It will only create the release tag if both the Python and Javascript side
# versions are the same, otherwise the version number would be ambiguous

name: Create Release Tag

on:
  push:
    branches:
      - 'main'

jobs:
  create-tag:
    name: Create Release Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Get current version (Python side)
        run: echo "current_version_py=$(grep "version" python_rpc/setup.cfg | cut -d ' ' -f 3 | tr -d '\r')" >> $GITHUB_ENV

      - name: Get current version (Javascript side)
        run: echo "current_version_js=$(grep "version" javascript_rpc/package.json | cut -d '"' -f 4)" >> $GITHUB_ENV

      - name: Check if versions match
        run: |
          if [[ "${{ env.current_version_py }}" == "${{ env.current_version_js }}" ]];
          then
            echo "Versions match! Creating release tag..."
          else
            echo "Versions do not match. Exiting..."
            exit 1
          fi

      - name: Create Release Tag
        env:
          commit_name: bot-edgepi
          commit_email: bot@edgepi.com
          username: bot-edgepi
        run: |
          git config user.name ${{ env.commit_name }}
          git config user.email ${{ env.commit_email }}
          git tag -a release/v${{ env.current_version_py }} -m "tag release version ${{ env.current_version_py }}"
          git push origin release/v${{ env.current_version_py }}
