# This workflow will use the pushed release tag to create a GitHub release

name: Create GitHub Release

on:
  push:
    tags:
      - release/* 

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.12.0
