name: Publish Package to npm
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Copy Proto Files
        run: |
          mkdir -p javascript_rpc/edgepi_rpc_protos
          cp *.proto javascript_rpc/edgepi_rpc_protos
          cp LICENSE javascript_rpc

      - name: Install and Test
        run: |
          cd javascript_rpc
          npm install
          npm test

      - name: Publish to npm
        run: |
          cd javascript_rpc
          VERSION=$(cat package.json | jq -r .version)
          if npm view @edgepi-cloud/edgepi-rpc-protobuf@beta versions --json | grep -q $VERSION
          then
            npm dist-tag add @edgepi-cloud/edgepi-rpc-protobuf@$VERSION latest
            npm dist-tag rm @edgepi-cloud/edgepi-rpc-protobuf beta
          else
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
