name: Publish Package to npm
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Copy Proto Files
        run: |
          mkdir -p javascript_rpc/edgepi_rpc_protos
          cp *.proto javascript_rpc/edgepi_rpc_protos/

      - name: Install and Test
        run: |
          cd javascript_rpc
          npm install
          npm test

      - name: Update Latest Tag
        run: |
          cd javascript_rpc
          BETA_VERSION=$(npm view @edgepi-cloud/edgepi-rpc-protobuf dist-tags.beta)
          if [ -z "$BETA_VERSION" ]
          then
            echo "Error: No beta version found for package-name."
            exit 1
          fi
          npm dist-tag add @edgepi-cloud/edgepi-rpc-protobuf@$BETA_VERSION latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
