name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Publish to PyPi and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install protobuf compiler
      run: |
        wget https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip
        unzip protoc-23.4-linux-x86_64.zip
    - name: Compile protos
      run: ./bin/protoc -I=. --python_out=./src-python/edgepirpc/protos ./*.proto
    - name: Install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install twine build
    - name: Build Package
      run: |
        python -m build
    - name: Publish Package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
