name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Publish to PyPi and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd python_rpc
        python -m pip install --upgrade pip
        pip install -r requirements-build.txt
    - name: Run Tests
      run: |
        pytest python_rpc/tests
    - name: Build Package
      run: |
        cd python_rpc
        python -m build
    - name: Publish Package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: python_rpc/dist