name: Build and Release

on:
  push:
    branches:
      - staging

jobs:
  build-and-publish:
    name: Publish to TestPyPi and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine build
    - name: Run Tests
      run: |
        pytest
    - name: Build Package
      run: |
        python -m build python_rpc
    - name: Publish Package to TestPyPI
      run: twine upload --repository testpypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
