name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  test-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Copy Proto Files
        run: |
          mkdir -p javascript_rpc/edgepi_rpc_protos
          cp *.proto javascript_rpc/edgepi_rpc_protos/
      - name: Install and Test
        run: |
          cd javascript_rpc
          npm install
          npm test
      - name: Cleanup Proto Files
        run: |
          rm -rf javascript_rpc/edgepi_rpc_protos
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd python_rpc
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Tests
        run: |
          pytest python_rpc/tests
