# This workflow updates the versions in `setup.cfg` and `package.json`
# to the version at the root of the repo

name: Update Versions

on:
  push:
    branches:
      - 'dev'

jobs:
  update-versions:
    name: Update Versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Get root version
        run: echo "root_version=$(grep "version =" version | cut -d ' ' -f 3)" >> $GITHUB_ENV

      - name: Update version (Python side)
        run: |
          sed -i 's/version = [0-9]\+\.[0-9]\+\.[0-9]\+/version = ${{ env.root_version }}/g' python_rpc/setup.cfg

      - name: Update version (JavaScript side)
        run: |
          sed -i 's/"version": "[0-9]\+\.[0-9]\+\.[0-9]\+"/"version": "${{ env.root_version }}"/g' javascript_rpc/package.json

      - name: Push version updates
        env:
          commit_name: bot-edgepi
          commit_email: bot@edgepi.com
          username: bot-edgepi
        run: |
          git config user.name ${{ env.commit_name }}
          git config user.email ${{ env.commit_email }}
          git add .
          git commit -m "bump project versions to ${{ env.root_version }} [skip ci]"
          git push origin dev
